# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_grid_fn <- function(d, x_sd, x_sd_mult = 1.5, n_pts = 11L, min_dist = 15) {
    .Call('debtLimits_d_grid_fn', PACKAGE = 'debtLimits', d, x_sd, x_sd_mult, n_pts, min_dist)
}

e_grid_fn <- function(x_sd, n_pts = 7L, d_tri = FALSE) {
    .Call('debtLimits_e_grid_fn', PACKAGE = 'debtLimits', x_sd, n_pts, d_tri)
}

Q_init <- function(d_grid, d, R) {
    .Call('debtLimits_Q_init', PACKAGE = 'debtLimits', d_grid, d, R)
}

p_init_d_i <- function(params, p, d, An, Bn, Cn, def, i) {
    .Call('debtLimits_p_init_d_i', PACKAGE = 'debtLimits', params, p, d, An, Bn, Cn, def, i)
}

p_init_d <- function(params, p, d, An, Bn, Cn, def) {
    .Call('debtLimits_p_init_d', PACKAGE = 'debtLimits', params, p, d, An, Bn, Cn, def)
}

q_fn <- function(R, p, trans, lambda, phi, n, cont_type, G, An, def) {
    .Call('debtLimits_q_fn', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, cont_type, G, An, def)
}

q_d_p <- function(R, p, trans, lambda, phi, n, cont_type, d_type, G, An, Bn, def) {
    .Call('debtLimits_q_d_p', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, cont_type, d_type, G, An, Bn, def)
}

q_d_p_num_i <- function(R, p, trans, lambda, phi, n, i, cont_type, G, An, def) {
    .Call('debtLimits_q_d_p_num_i', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, i, cont_type, G, An, def)
}

d_prime <- function(i_x, d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, print_level = 1L, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_d_prime', PACKAGE = 'debtLimits', i_x, d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, print_level, tol, maxit)
}

q_e <- function(d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level = 1L, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_q_e', PACKAGE = 'debtLimits', d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level, tol, maxit)
}

q_hat_fn <- function(d, p, d_bar, qhat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level = 1L, tol = 1e-05, maxit = 50L, d_tol = 1e-05, d_maxit = 20L) {
    .Call('debtLimits_q_hat_fn', PACKAGE = 'debtLimits', d, p, d_bar, qhat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level, tol, maxit, d_tol, d_maxit)
}

q_hat_mat <- function(P, d_bar, QHat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level = 0L, tol = 1e-04, maxit = 50L, d_tol = 1e-05, d_maxit = 20L) {
    .Call('debtLimits_q_hat_mat', PACKAGE = 'debtLimits', P, d_bar, QHat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, print_level, tol, maxit, d_tol, d_maxit)
}

d_prime_mat <- function(d_bar, QHat, Q, d_grid, G, lambda, e_grid, trans, coeff, tri, D_prime_0, D_prime_0_flag, print_level = 1L, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_d_prime_mat', PACKAGE = 'debtLimits', d_bar, QHat, Q, d_grid, G, lambda, e_grid, trans, coeff, tri, D_prime_0, D_prime_0_flag, print_level, tol, maxit)
}

qe_mat <- function(d_bar, QHat, Q, d_grid, G, lambda, e_grid, trans, coeff, tri, D_prime_0, D_prime_0_flag, print_level = 0L, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_qe_mat', PACKAGE = 'debtLimits', d_bar, QHat, Q, d_grid, G, lambda, e_grid, trans, coeff, tri, D_prime_0, D_prime_0_flag, print_level, tol, maxit)
}

v_surp <- function(d, coeff, G, tri) {
    .Call('debtLimits_v_surp', PACKAGE = 'debtLimits', d, coeff, G, tri)
}

surp <- function(d, coeff, G = 0, tri = FALSE) {
    .Call('debtLimits_surp', PACKAGE = 'debtLimits', d, coeff, G, tri)
}

surp_poly <- function(d, coeff, G = 0) {
    .Call('debtLimits_surp_poly', PACKAGE = 'debtLimits', d, coeff, G)
}

surp_tri <- function(d, coeff, G = 0) {
    .Call('debtLimits_surp_tri', PACKAGE = 'debtLimits', d, coeff, G)
}

d_surp_tri <- function(d, coeff, G = 0) {
    .Call('debtLimits_d_surp_tri', PACKAGE = 'debtLimits', d, coeff, G)
}

d_triangle <- function(x, a, b, c) {
    .Call('debtLimits_d_triangle', PACKAGE = 'debtLimits', x, a, b, c)
}

p_triangle <- function(x, a, b, c) {
    .Call('debtLimits_p_triangle', PACKAGE = 'debtLimits', x, a, b, c)
}

d_triangle2 <- function(x, a, b, c) {
    .Call('debtLimits_d_triangle2', PACKAGE = 'debtLimits', x, a, b, c)
}

q_triangle <- function(q, a, b, c) {
    .Call('debtLimits_q_triangle', PACKAGE = 'debtLimits', q, a, b, c)
}

zed <- function(p, d, params, An, Cn, def) {
    .Call('debtLimits_zed', PACKAGE = 'debtLimits', p, d, params, An, Cn, def)
}

zed_d <- function(p, d, dprime, params, An, Cn, def) {
    .Call('debtLimits_zed_d', PACKAGE = 'debtLimits', p, d, dprime, params, An, Cn, def)
}

zed_2 <- function(p, d, params, An, Bn, Cn, def) {
    .Call('debtLimits_zed_2', PACKAGE = 'debtLimits', p, d, params, An, Bn, Cn, def)
}

zed_2_num <- function(p, d, params, Cn, An, def) {
    .Call('debtLimits_zed_2_num', PACKAGE = 'debtLimits', p, d, params, Cn, An, def)
}

zed_2_num_d_i <- function(p, d, params, i, An, Cn, def) {
    .Call('debtLimits_zed_2_num_d_i', PACKAGE = 'debtLimits', p, d, params, i, An, Cn, def)
}

zed_2_ana <- function(p, d, params, An, Bn, Cn, def) {
    .Call('debtLimits_zed_2_ana', PACKAGE = 'debtLimits', p, d, params, An, Bn, Cn, def)
}

ziter <- function(P, d_bar, QHat, d_grid, e_grid, tri, D_prime_0, D_prime_0_flag, params, An, Cn, print_level = 0L, tol = 1e-04, maxit = 100L, q_tol = 1e-04, q_maxit = 50L, d_tol = 1e-05, d_maxit = 20L, Q_out = FALSE) {
    .Call('debtLimits_ziter', PACKAGE = 'debtLimits', P, d_bar, QHat, d_grid, e_grid, tri, D_prime_0, D_prime_0_flag, params, An, Cn, print_level, tol, maxit, q_tol, q_maxit, d_tol, d_maxit, Q_out)
}

