# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_grid_fn <- function(d, x_sd, x_sd_mult = 1.1, n_pts = 7L) {
    .Call('debtLimits_d_grid_fn', PACKAGE = 'debtLimits', d, x_sd, x_sd_mult, n_pts)
}

e_grid_fn <- function(x_sd, n_pts = 7L) {
    .Call('debtLimits_e_grid_fn', PACKAGE = 'debtLimits', x_sd, n_pts)
}

Q_init <- function(d_grid, d, R) {
    .Call('debtLimits_Q_init', PACKAGE = 'debtLimits', d_grid, d, R)
}

p_init_d_i <- function(params, p, d, An, Bn, Cn, def, i) {
    .Call('debtLimits_p_init_d_i', PACKAGE = 'debtLimits', params, p, d, An, Bn, Cn, def, i)
}

p_init_d <- function(params, p, d, An, Bn, Cn, def) {
    .Call('debtLimits_p_init_d', PACKAGE = 'debtLimits', params, p, d, An, Bn, Cn, def)
}

q_fn <- function(R, p, trans, lambda, phi, n, cont_type, G, An, def) {
    .Call('debtLimits_q_fn', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, cont_type, G, An, def)
}

q_d_p <- function(R, p, trans, lambda, phi, n, cont_type, d_type, G, An, Bn, def) {
    .Call('debtLimits_q_d_p', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, cont_type, d_type, G, An, Bn, def)
}

q_d_p_num_i <- function(R, p, trans, lambda, phi, n, i, cont_type, G, An, def) {
    .Call('debtLimits_q_d_p_num_i', PACKAGE = 'debtLimits', R, p, trans, lambda, phi, n, i, cont_type, G, An, def)
}

d_prime <- function(i_x, d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, verbose = TRUE, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_d_prime', PACKAGE = 'debtLimits', i_x, d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, verbose, tol, maxit)
}

q_e <- function(d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, verbose = TRUE, tol = 1e-05, maxit = 20L) {
    .Call('debtLimits_q_e', PACKAGE = 'debtLimits', d, d_bar, qhat, Q, d_grid, G, lambda, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, verbose, tol, maxit)
}

q_iter_fn <- function(d, p, d_bar, qhat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, verbose = TRUE, tol = 1e-05, maxit = 50L, d_tol = 1e-05, d_maxit = 20L) {
    .Call('debtLimits_q_iter_fn', PACKAGE = 'debtLimits', d, p, d_bar, qhat, Q, d_grid, R, G, lambda, phi, e_grid, coeff, tri, D_prime_0, D_prime_0_flag, trans, verbose, tol, maxit, d_tol, d_maxit)
}

v_surp <- function(d, coeff, G, tri) {
    .Call('debtLimits_v_surp', PACKAGE = 'debtLimits', d, coeff, G, tri)
}

surp <- function(d, coeff, G = 0, tri = FALSE) {
    .Call('debtLimits_surp', PACKAGE = 'debtLimits', d, coeff, G, tri)
}

surp_poly <- function(d, coeff, G = 0) {
    .Call('debtLimits_surp_poly', PACKAGE = 'debtLimits', d, coeff, G)
}

surp_tri <- function(d, coeff, G = 0) {
    .Call('debtLimits_surp_tri', PACKAGE = 'debtLimits', d, coeff, G)
}

d_surp_tri <- function(d, coeff, G = 0) {
    .Call('debtLimits_d_surp_tri', PACKAGE = 'debtLimits', d, coeff, G)
}

d_triangle <- function(x, a, b, c) {
    .Call('debtLimits_d_triangle', PACKAGE = 'debtLimits', x, a, b, c)
}

p_triangle <- function(x, a, b, c) {
    .Call('debtLimits_p_triangle', PACKAGE = 'debtLimits', x, a, b, c)
}

d_triangle2 <- function(x, a, b, c) {
    .Call('debtLimits_d_triangle2', PACKAGE = 'debtLimits', x, a, b, c)
}

zed <- function(p, d, params, An, Cn, def) {
    .Call('debtLimits_zed', PACKAGE = 'debtLimits', p, d, params, An, Cn, def)
}

zed_2 <- function(p, d, params, An, Bn, Cn, def) {
    .Call('debtLimits_zed_2', PACKAGE = 'debtLimits', p, d, params, An, Bn, Cn, def)
}

zed_2_num <- function(p, d, params, Cn, An, def) {
    .Call('debtLimits_zed_2_num', PACKAGE = 'debtLimits', p, d, params, Cn, An, def)
}

zed_2_num_d_i <- function(p, d, params, i, An, Cn, def) {
    .Call('debtLimits_zed_2_num_d_i', PACKAGE = 'debtLimits', p, d, params, i, An, Cn, def)
}

zed_2_ana <- function(p, d, params, An, Bn, Cn, def) {
    .Call('debtLimits_zed_2_ana', PACKAGE = 'debtLimits', p, d, params, An, Bn, Cn, def)
}

